name: Events Demo 1
on:
  # define a list of activity types which should trigger this workflow
  pull_request:
    types:
      - opened
      # - edited
    branches:
      - main
      - "dev-*" # all branches with dev- in the start - dev-navbar
      - "feat/**" # all branches with chars and / after the initial / - feat/navbar/darkmode

  workflow_dispatch:

  # event filter - only trigger event when pushing to specified branch
  push:
    branches:
      - main
      - "dev-*" # all branches with dev- in the start - dev-navbar
      - "feat/**" # all branches with chars and / after the initial / - feat/navbar/darkmode
    branches-ignore:
      - "bug-*" # ignore all push requests from branches with pattern "bug-"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."