name: Test Project
on: push
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        # define the predefined actions you want to use
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        # action-specific keyword
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci 
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        # define the predefined actions you want to use
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        # action-specific keyword
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci 
      - name: Build project
        # targets the build.js script in this application
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."