name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context 
        # output the environment metadata made available by github
        # make it readable to user using the toJson github function
        run: echo "${{ toJson(github) }}"